--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/AntiDupeTiles
build-by-default: true
branches:
- PM5
projects:
  AntiDupeTiles:
    path: ""
    lint:
       phpstan: false
...
